version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ShootingGameDB
      - redis
    environment:
      DATABASE_URL: postgresql://admin:admin@ShootingGameDB:5432/shootinggame
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    volumes:
      - .:/src
    networks:
      - api_postgres
      - api_redis

  ShootingGameDB:
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shootinggame
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_postgres

  redis:
    image: redis
    networks:
      - api_redis
      
volumes:
  pgdata:     

networks:
  api_postgres:
  api_redis: